name: bison_design_system
description: "A good and nice design system for Flutter apps"

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.2
homepage:

environment:
  sdk: ^3.10.4
  flutter: ^3.38.5

dependencies:
  flutter:
    sdk: flutter

  # The intl package provides internationalization and localization
  # support, including message formatting and date/time formatting.
  intl: ^0.20.2

  disable_web_context_menu: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.26.3
  dart_pre_commit: ^6.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Atkinson Hyperlegible Next
      fonts:
        # Regular & Italics (Weight 400)
        - asset: lib/assets/fonts/AtkinsonHyperlegibleNext-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/AtkinsonHyperlegibleNext-Italic.ttf
          weight: 400
          style: italic

        # Light (Weight 300)
        - asset: lib/assets/fonts/AtkinsonHyperlegibleNext-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/AtkinsonHyperlegibleNext-LightItalic.ttf
          weight: 300
          style: italic

        # ExtraLight (Weight 200)
        - asset: lib/assets/fonts/AtkinsonHyperlegibleNext-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/AtkinsonHyperlegibleNext-ExtraLightItalic.ttf
          weight: 200
          style: italic

        # Medium (Weight 500)
        - asset: lib/assets/fonts/AtkinsonHyperlegibleNext-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/AtkinsonHyperlegibleNext-MediumItalic.ttf
          weight: 500
          style: italic

        # SemiBold (Weight 600)
        - asset: lib/assets/fonts/AtkinsonHyperlegibleNext-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/AtkinsonHyperlegibleNext-SemiBoldItalic.ttf
          weight: 600
          style: italic

        # Bold (Weight 700)
        - asset: lib/assets/fonts/AtkinsonHyperlegibleNext-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/AtkinsonHyperlegibleNext-BoldItalic.ttf
          weight: 700
          style: italic

        # ExtraBold (Weight 800)
        - asset: lib/assets/fonts/AtkinsonHyperlegibleNext-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/AtkinsonHyperlegibleNext-ExtraBoldItalic.ttf
          weight: 800
          style: italic

dart_pre_commit:
  analyze:
    ignore-unstaged-files: true
  outdated: false
