name: Continuous Integration for Flutter applications

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    uses: fermi-ad/.github/.github/workflows/flutter-integration.yaml@6e196e87b3b79167b57bf18cf3ca0cfcd88f958f
    secrets: inherit
    permissions:
      contents: write
      issues: write
      pull-requests: write
    with:
      # Change to true to pull in git submodules during build
      pull-git-submodules: false
      coverage-exclude: "|tool/setup_git_hooks.dart|.*\\.g\\.dart$"
